package com.overcode250204.smartlogicticssystem.dataSeeder;

import com.overcode250204.smartlogicticssystem.entities.Supplier;
import com.overcode250204.smartlogicticssystem.entities.SupplierInvoice;
import com.overcode250204.smartlogicticssystem.entities.SupplierInvoicePayment;
import com.overcode250204.smartlogicticssystem.entities.User;
import com.overcode250204.smartlogicticssystem.enums.InvoiceStatus;
import com.overcode250204.smartlogicticssystem.enums.PaymentMethod;
import com.overcode250204.smartlogicticssystem.repositories.SupplierInvoicePaymentRepository;
import com.overcode250204.smartlogicticssystem.repositories.SupplierInvoiceRepository;
import com.overcode250204.smartlogicticssystem.repositories.SupplierRepository;
import com.overcode250204.smartlogicticssystem.repositories.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;

@Component
@RequiredArgsConstructor
@Slf4j
public class SupplierInvoiceDataSeeder implements DataSeeder {

    private final SupplierRepository supplierRepository;
    private final SupplierInvoiceRepository supplierInvoiceRepository;
    private final SupplierInvoicePaymentRepository paymentRepository;
    private final UserRepository userRepository;

    @Override
    public int getOrder() {
        return 15;
    }

    @Override
    @Transactional
    public void seed() {
        List<Supplier> suppliers = supplierRepository.findAll().stream()
                .sorted(Comparator.comparing(Supplier::getSupplierId))
                .toList();
        if (suppliers.size() < 4) {
            throw new IllegalStateException("At least four suppliers are required for invoice seed data");
        }

        LocalDate today = LocalDate.now();
        List<InvoiceSeed> invoices = List.of(
                new InvoiceSeed("SUP-INV-SEED-001", suppliers.get(0), today.minusDays(10), today.plusDays(20),
                        "25000000", "0", InvoiceStatus.UNPAID, null, null, null),
                new InvoiceSeed("SUP-INV-SEED-002", suppliers.get(1), today.minusDays(20), today.plusDays(10),
                        "40000000", "15000000", InvoiceStatus.PARTIAL_PAID,
                        "15000000", today.minusDays(5), PaymentMethod.BANK_TRANSFER),
                new InvoiceSeed("SUP-INV-SEED-003", suppliers.get(2), today.minusDays(40), today.minusDays(10),
                        "18000000", "18000000", InvoiceStatus.PAID,
                        "18000000", today.minusDays(15), PaymentMethod.CASH),
                new InvoiceSeed("SUP-INV-SEED-004", suppliers.get(3), today.minusDays(60), today.minusDays(30),
                        "32000000", "0", InvoiceStatus.OVERDUE, null, null, null)
        );

        User admin = userRepository.findByEmail("admin@logistics.com")
                .orElseThrow(() -> new IllegalStateException("Seed admin user not found"));
        invoices.forEach(seed -> createInvoiceAndPayment(seed, admin));
        log.info("Supplier-invoice and payment seed data completed.");
    }

    private void createInvoiceAndPayment(InvoiceSeed seed, User admin) {
        SupplierInvoice invoice = supplierInvoiceRepository.findByInvoiceCode(seed.invoiceCode())
                .orElseGet(() -> {
                    BigDecimal total = new BigDecimal(seed.totalAmount());
                    BigDecimal paid = new BigDecimal(seed.paidAmount());

                    SupplierInvoice created = new SupplierInvoice();
                    created.setInvoiceCode(seed.invoiceCode());
                    created.setSupplier(seed.supplier());
                    created.setInvoiceDate(seed.invoiceDate());
                    created.setDueDate(seed.dueDate());
                    created.setTotalAmount(total);
                    created.setPaidAmount(paid);
                    created.setRemainingAmount(total.subtract(paid));
                    created.setStatus(seed.status());
                    created.setNote("Deterministic test invoice generated by the seed profile");
                    created.setIsActive(true);
                    return supplierInvoiceRepository.save(created);
                });

        if (seed.paymentAmount() == null) {
            return;
        }

        BigDecimal amount = new BigDecimal(seed.paymentAmount());
        if (paymentRepository.existsByInvoice_IdAndAmountAndPaymentDate(
                invoice.getId(), amount, seed.paymentDate())) {
            return;
        }

        SupplierInvoicePayment payment = new SupplierInvoicePayment();
        payment.setInvoice(invoice);
        payment.setAmount(amount);
        payment.setPaymentDate(seed.paymentDate());
        payment.setPaymentMethod(seed.paymentMethod());
        payment.setNote("Seed payment");
        payment.setCreatedBy(admin);
        paymentRepository.save(payment);
    }

    private record InvoiceSeed(
            String invoiceCode,
            Supplier supplier,
            LocalDate invoiceDate,
            LocalDate dueDate,
            String totalAmount,
            String paidAmount,
            InvoiceStatus status,
            String paymentAmount,
            LocalDate paymentDate,
            PaymentMethod paymentMethod
    ) {
    }
}
